# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nodes', '0006_auto_20160107_1307'),
        ('Profiles', '0002_auto_20160107_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='home_directory',
        ),
        migrations.AddField(
            model_name='profile',
            name='home',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Nodes.Node'),
            preserve_default=False,
        ),
    ]
