# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-04 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nodes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='provider',
        ),
        migrations.AddField(
            model_name='link',
            name='provider1',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='provider2',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='node_id',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='node1',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='link',
            name='node2',
            field=models.CharField(max_length=1000),
        ),
    ]
