# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-04 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nodes', '0003_remove_node_node_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='relation',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
