# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-05 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nodes', '0004_link_relation'),
    ]

    import datetime
    operations = [
        migrations.AddField(
            model_name='node',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date.today()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date.today()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='url_hash',
            field=models.CharField(default='', max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='url',
            name='image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
